PublicIPAddress support
crossplane/provider-azure pull request #264
Opened 2021-06-21 08:39 UTC by vaspahomov

Hello! 

I want to add VM instances support in crossplane/provider-azure. 

This is first part of big patch with Public IP addresses support

### Description of your changes

Add support of Public IP Address.
Fixes #

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Same like in other resources like Subnet and VisrtualNetwork. And also manually tested

[contribution process]: https://git.io/fj2m9

2021-09-21 19:02 UTC, ulucinar requested changes

2021-09-21 19:04 UTC, ulucinar reviewed
Thank you @vaspahomov for your work on this PR! Could you please rebase this PR and make sure all your commits are signed following the guide [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits). We also require them to be signed-off using something similar to `git commit -s`. `git log --show-signature` should display commit signatures.

2021-09-22 14:09 UTC, ulucinar commented on pkg/controller/network/publicipaddress/managed.go
> +	}
```suggestion
```

2021-09-27 10:49 UTC, vaspahomov commented on pkg/controller/network/publicipaddress/managed.go
> +	return o, nil
I've add todo about update support. It's not very often case for now

2021-09-27 10:52 UTC, vaspahomov commented
Hi @ulucinar thank you! I've commit fixes

2021-11-29 10:48 UTC, ulucinar commented
Hi @vaspahomov,
Thank you for working on this PR. I'm planning to merge this and maybe address some remaining comments in a follow-up PR? What do you think?

2021-11-29 17:32 UTC, ulucinar approved these changes

2021-11-29 17:33 UTC, ulucinar commented
Thank you very much @vaspahomov, merging this PR.

2021-11-29 17:33 UTC, merged

2021-11-30 08:09 UTC, ulucinar commented
@vaspahomov, I've just opened a follow-up [PR](https://github.com/crossplane/provider-azure/pull/309).